# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'callyourname.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_homework(object):
    def setupUi(self, Form_homework):
        Form_homework.setObjectName("Form_homework")
        Form_homework.resize(637, 407)
        self.groupBox_call = QtWidgets.QGroupBox(Form_homework)
        self.groupBox_call.setGeometry(QtCore.QRect(30, 20, 581, 361))
        self.groupBox_call.setObjectName("groupBox_call")
        self.pushButton_call = QtWidgets.QPushButton(self.groupBox_call)
        self.pushButton_call.setGeometry(QtCore.QRect(290, 180, 75, 23))
        self.pushButton_call.setObjectName("pushButton_call")
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox_call)
        self.lineEdit_name.setGeometry(QtCore.QRect(150, 180, 131, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_name = QtWidgets.QLabel(self.groupBox_call)
        self.label_name.setGeometry(QtCore.QRect(80, 180, 54, 21))
        self.label_name.setObjectName("label_name")
        self.label_path = QtWidgets.QLabel(self.groupBox_call)
        self.label_path.setGeometry(QtCore.QRect(80, 90, 61, 41))
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(self.groupBox_call)
        self.lineEdit_path.setGeometry(QtCore.QRect(150, 100, 381, 20))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.pushButton_path = QtWidgets.QPushButton(self.groupBox_call)
        self.pushButton_path.setGeometry(QtCore.QRect(230, 130, 75, 23))
        self.pushButton_path.setObjectName("pushButton_path")
        self.tableWidget_call = QtWidgets.QTableWidget(self.groupBox_call)
        self.tableWidget_call.setGeometry(QtCore.QRect(80, 230, 451, 91))
        self.tableWidget_call.setObjectName("tableWidget_call")
        self.tableWidget_call.setColumnCount(0)
        self.tableWidget_call.setRowCount(0)

        self.retranslateUi(Form_homework)
        QtCore.QMetaObject.connectSlotsByName(Form_homework)

    def retranslateUi(self, Form_homework):
        _translate = QtCore.QCoreApplication.translate
        Form_homework.setWindowTitle(_translate("Form_homework", "Form"))
        self.groupBox_call.setTitle(_translate("Form_homework", "点名窗口"))
        self.pushButton_call.setText(_translate("Form_homework", "随机点名"))
        self.label_name.setText(_translate("Form_homework", "姓名："))
        self.label_path.setText(_translate("Form_homework", "名单路径："))
        self.pushButton_path.setText(_translate("Form_homework", "选择路径"))
        
